### ISSUE TITLE
EndUser Authentification

### ISSUE THREAD

**Issue by ghost** [xively/xively-mobile-sdk-android#1]
Hi
I'm having trouble while using the Xively Android SDK when I try to log-in with a end-user account.

Step to reproduce : log-in with a end-user account

The SDK failed with an **Internal Error** message.
The reason seem to be in the [BlueprintWebService.java line 361](https://github.com/xively/xively-mobile-sdk-android/blob/master/XivelySDKAndroid/src/main/java/com/xively/internal/rest/blueprint/BlueprintWebServices.java#L361) :

`String userId = (String)endUserMap.get("id");` 
might be 
`String userId = (String)endUserMap.get("userId");`

With this minor update, I'm now able to login with my end-user account

Seb

**Comment by Kresshy** [comment]
Hi, sorry for the delayed answer this one is resolved by now!
